kind: pipeline
type: docker
name: Azure Function App

image_pull_secrets:
- dockerconfig

steps:
- name: Build and upload function app
  environment:
    AZURE_SP:
     from_secret: AZURE_SP
    AZURE_SP_PASSWORD:
     from_secret: AZURE_SP_PASSWORD
    AZURE_SP_TENANT:
     from_secret: AZURE_SP_TENANT
    FUNCTION_APP_NAME:
     from_secret: FUNCTION_APP_NAME
  image: registry.kmlabz.com/tormakris/ubuntu-azure-cli
  commands:
  - az login --service-principal -u $AZURE_SP -p $AZURE_SP_PASSWORD --tenant $AZURE_SP_TENANT
  - func azure functionapp publish $FUNCTION_APP_NAME --python --build=local
