kind: pipeline
type: docker
name: Azure Function App

steps:
- name: Build and upload function app
  environment:
    AZURE_SP:
     from_secret: AZURE_SP
    AZURE_SP_PASSWORD:
     from_secret: AZURE_SP_PASSWORD
    AZURE_SP_TENANT:
     from_secret: AZURE_SP_TENANT
    FUNCTION_APP_NAME:
     from_secret: FUNCTION_APP_NAME
  image: mcr.microsoft.com/azure-cli
  commands:
  - apk add npm
  - npm i -g azure-functions-core-tools@3 --unsafe-perm true
  - az login --service-principal -u $AZURE_SP -p $AZURE_SP_PASSWORD --tenant $AZURE_SP_TENANT
  - func azure functionapp publish $FUNCTION_APP_NAME --python
